### ISSUE TITLE
"Error getting apiKey"

### ISSUE THREAD

**Issue by WPires** [halipso/php-steam-tradeoffers#1]
Hello,

I'm having the following problem:
Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /var/sentora/hostdata/zadmin/public_html/csgofate_com/system/unirest/classRequest.php on line 423
Error getting apiKey. Code:302

You know how to solve this?

Att. Washington.

**Comment by halipso** [comment]
Check if sessionID and cookies are correct.

**Comment by WPires** [comment]
I managed to fixed. Thanks.
