### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ghost** [halipso/php-steam-tradeoffers#10]
Hello 
I am getting error in steam.class.php when i run script, i have not make any changes in script.
error is :- syntax error, unexpected T_STRING, expecting ')' in 
Parse error: syntax error, unexpected '[' in C:\OpenServer\domains\php-steam-tradeoffers-master\classes\steam.class.php on line 52

Please help, also i have lot of questions but i want to short out one by one.

**Comment by Darindaa** [comment]
redownload the steam.class.php and replace it with the newly downloaded file, i think you misplaced the syntax by mistake.
