### ISSUE TITLE
error code 302

### ISSUE THREAD

**Issue by emdy** [halipso/php-steam-tradeoffers#16]
Get steamid and cookie currect, but when i make a trade i get apiKey error 302. If i want load my inventory i get 302... how fix?

**Comment by SzymonLisowiec** [comment]
You can try create new apiKey.

**Comment by onurdogucu** [comment]
emdy, I have cookie problem, I always get "Invalid Response" error when I try to getInventory. Do you know how to fix this ?

**Comment by emdy** [comment]
@SzymonLisowiec Its ok when i create new ApiKey, but i cant load inventory. I tkink its php-offer code problem!
I tryd do all stuff even send a trade, so stay calm and i will update code.
@OwnurD php-login working well, but it seems php-offer code problems. And check if you dont get NULL result for session and cookie.
