### ISSUE TITLE
What is it Sessino iD?

### ISSUE THREAD

**Issue by oleghalin** [halipso/php-steam-tradeoffers#24]
What is it Sessino iD? and can i use it without node ?

**Comment by emdy** [comment]
Dude your dumb as rock - google it lol lazy kid.

**Comment by oleghalin** [comment]
Omg. And who is kid? I just ask. Keep calm man.

**Comment by emdy** [comment]
There is like 2/4 who is lazy and asks some stupid questions.

**Comment by rumblefrog** [comment]
For future people: https://github.com/SzymonLisowiec/php-steamlogin

**Comment by Robinlemon** [comment]
@oleghalin A SessonID is a UUID (Unique Universal Identifier) which corresponds to our Steam profile, thus when you have it as a cookie, Steam can directly see it's you; so in theory, yes you could guess until you get somebody SessionID, however, you'd also need their steamLogon cookie and their steamLogonSecure cookie. I believe Steam also accounts for IPs too.

**Comment by emdy** [comment]
@Robinlemon dont answer if you dont know about steam! Never quess.

**Comment by Robinlemon** [comment]
@emdy Where did I make a presumption.
