### ISSUE TITLE
getOfferToken from Steam Web API

### ISSUE THREAD

**Issue by falahati** [halipso/php-steam-tradeoffers#25]
Hi,

I have a bot that I want to use to send offers to other user without adding them on steam. Yet I don't want to ask them about their Steam Trade Offer Token directly,
Is there a way to use the Steam Web API (OpenID) and let them login and then extract the token for the offer?
https://steamcommunity.com/dev

**Comment by emdy** [comment]
User need to provide trade link and than you can get Token and use it!

**Comment by falahati** [comment]
Sry, I had no idea that OpenID API only gave us basic user information.
So the only other way that doesn't require asking for token from user is to ask for username and password and then steam guard code to do authentication and then retrieve the trade link automatically.

**Comment by emdy** [comment]
True, but its not hard for user to put simple trade url so its ok, for me users domt go mad for it :D
