### ISSUE TITLE
The confirmation

### ISSUE THREAD

**Issue by tabuna** [halipso/php-steam-tradeoffers#30]
Hi, how to implement confirmation of exchange through a mobile device?

**Comment by emdy** [comment]
No one gives you done lib, i can sell it for 20€.

**Comment by tabuna** [comment]
Thanks, but I already had written

**Comment by Govind13100** [comment]
Hie there, i want to accept tradeoffer automatically , how do achieve this ???

**Comment by emdy** [comment]
Research in github, dont be lazy

**Comment by Govind13100** [comment]
I did and achieved already !!! :-)

**Comment by emdy** [comment]
Than good job close if ur done
