### ISSUE TITLE
getHoldDuration

### ISSUE THREAD

**Issue by ReptoxX** [halipso/php-steam-tradeoffers#31]
Hello,

Is there a way to add this function ? 
As from the version with node.js?

Regards,
ReptoxX

**Comment by emdy** [comment]
you can do all stuff with node and php.

**Comment by ReptoxX** [comment]
This is not helpful.
I know, but i am not into node, so i am asking if the lib creator here adds this function.

**Comment by emdy** [comment]
u can get duration by steam API
