### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by NadirRed** [halipso/php-steam-tradeoffers#34]
im trying to use this lib to send steam offer
and i get Invalid Response as result

**Comment by emdy** [comment]
Losers make ur own lib this lib ir broken and if u wana buy full website for 100€ than i can give u!!!

**Comment by NadirRed** [comment]
@emdy im gonna keep trying untill i build my own steam trade lib and im gonna upload it for free ! So that ppl like you can suck it ! Loser

**Comment by emdy** [comment]
If u cant solve this lib error than sorry IT not for u mate!

**Comment by emdy** [comment]
And one thing i cant be loser because i have 2k month and i have roulete.. so ur loser

**Comment by NadirRed** [comment]
Good for you ! Now get lost

**Comment by emdy** [comment]
Hahahah sad and low life u have. Mad cuz bad :D
