### ISSUE TITLE
Array of cookies - Where to find?

### ISSUE THREAD

**Issue by adrianwesley** [halipso/php-steam-tradeoffers#4]
Hi Halipso,

Could you tell me how I do Array of cookies?

Can you help me?

**Comment by cymruu** [comment]
Hi @brk4tw just go to steamcommunity.com and paste this into URL 
javascript:alert(document.cookie);

**Comment by Qeam** [comment]
how to get the array of cookies in php ?

**Comment by cymruu** [comment]
@Qeam what do you mean? theyre stored in some variable so var_dump should return those
