### ISSUE TITLE
syntax error, unexpected T_STRING, expecting ')'

### ISSUE THREAD

**Issue by rahulchhlotre** [halipso/php-steam-tradeoffers#6]
Hello 
I am getting error in steam.class.php when i run script, i have not make any changes in script.
error is :-  syntax error, unexpected T_STRING, expecting ')' in /home/genuines/public_html/inhouse/shapingtechnology/demo/csgolucky/trade/classes/steam.class.php on line 33

Please help, also i have lot of questions but i want to short out one by one.

Thnaks

**Comment by cymruu** [comment]
It's not a forum, you shouldn't ask for help here. The issues are supposed to report issues with the library not your code

**Comment by rahulchhlotre** [comment]
Also can you tell me server requirements how many packages will need to install on server. please please we are not able to run this script.

please help us.
Thanks
