### ISSUE TITLE
it won't accept my session and cookies. 

### ISSUE THREAD

**Issue by Darindaa** [halipso/php-steam-tradeoffers#9]
mysession looks like this: http://steamcommunity.com/openid/id/7xxxxxx
cookie like this: jfe0r06bab7a3sekglxxxxxxxx

wut am i doing wrong?

Fatal error: Call to a member function find() on a non-object in C:\wamp\www\classes\steam.class.php on line 47

$steam->setup($_SESSION['T2SteamAuth'] , $cookie);

**Comment by ghost** [comment]
You need to get API key in the "Steam" and put it in the "steam.class.php .After that, my problem was resolved. Please tell me, where did you get cookies array? Is it true that session id it's a value, which we can see from the browser?
Sorry for my English.
